# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    groups:
      non-breaking-updates:
        patterns:
          - "*" # All dependecies that are minor or patch.
        update-types:
          - "minor"
          - "patch"
      serwist-updates:
        patterns:
          - "@serwist/*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
